

category_options = {
"Fortified":"Fortified",
"Red":"Red",
"Rose":"Rose",
"Sparkling":"Sparkling",
"White":"White",
"Dessert":"Dessert"
}



wine_rating = {
    
    '70':'70',
    '75':'75',
    '80':'80',
    '85':'85',
    '90':'90',
    '95':'95'
}

price_list ={
    '5':'5',
    '20':'20',
    '30':'30',
    '40':'40',
    '50':'50',
    '60':'60',
    '70':'70',
    '80':'80',
    '90':'90',
    '100':'100',
    '500':'500'
}


country = {            
"Cyprus" :"Cyprus",
"Turkey" : "Turkey",
"Switzerland":"Switzerland",
"Italy" :"Italy",
"New Zealand":"New Zealand",
"Uruguay":"Uruguay",
"Hungary":"Hungary",
"US":"US",
"China" :"China",
"Luxembourg"   :"Luxembourg",
"Czech Republic"     :"Czech Republic",
"US-France" :"US-France",
"Armenia"   :"Armenia",
"Romania"   :"Romania",
"Montenegro" :"Montenegro",
"Brazil" :"Brazil",
"Austria" :"Austria",
"Australia":"Australia",
"Germany":"Germany",
"Serbia" :"Serbia",
"Macedonia" :"Macedonia",
"Canada" :"Canada",
"South Korea" :"South Korea",
"Portugal" :"Portugal",
"Albania" :"Albania",
"Lithuania" :"Lithuania",
"Ukraine" :"Ukraine",
"Bulgaria" :"Bulgaria",
"Argentina" :"Argentina",
"Spain" :"Spain",
"Croatia" :"Croatia",
"Tunisia" :"Tunisia",
"England" :"England",
"Slovenia":"Slovenia",
"Egypt" :"Egypt",
"Greece"  :"Greece",
"India" :"India",
"Georgia"  :"Georgia",
"Morocco" :"Morocco",
"Moldova" :"Moldova",
"Chile":"Chile",
"France":"France",
"Global" :"Global",
"Slovakia":"Slovakia",
"Israel" :"Israel",
"Mexico" :"Mexico",
"South Africa" :"South Africa",
"Peru"  :"Peru",
"Japan":"Japan",
"Bosnia and Herzegovina" :"Bosnia and Herzegovina"  
 
}


vintage = {
'1621':'1621',
'1991':'1991',
'1965':'1965',
'1962':'1962',
'1947':'1947',
'2008':'2008',
'1827':'1827',
'1952':'1952',
'1868':'1868',
'1982':'1982',
'1860':'1860',
'2002':'2002',
'1978':'1978',
'2015':'2015',
'2007':'2007',
'1757':'1757',
'1955':'1955',
'2003':'2003',
'1150':'1150',
'1976':'1976',
'2005':'2005',
'1870':'1870',
'1992':'1992',
'2016':'2016',
'1988':'1988',
'1503':'1503',
'1969':'1969',
'1929':'1929',
'1907':'1907',
'1954':'1954',
'1882':'1882',
'1830':'1830',
'1996':'1996',
'1939':'1939',
'1984':'1984',
'1948':'1948',
'1531':'1531',
'2011':'2011',
'1875':'1875',
'1980':'1980',
'1908':'1908',
'1927':'1927',
'1492':'1492',
'1995':'1995',
'2012':'2012',
'1974':'1974',
'1877':'1877',
'1904':'1904',
'1985':'1985',
'1983':'1983',
'1869':'1869',
'1951':'1951',
'1957':'1957',
'1935':'1935',
'1945':'1945',
'1963':'1963',
'1821':'1821',
'2006':'2006',
'2014':'2014',
'2010':'2010',
'1852':'1852',
'1987':'1987',
'2017':'2017',
'1845':'1845',
'7200':'7200',
'1887':'1887',
'1993':'1993',
'1960':'1960',
'2001':'2001',
'1212':'1212',
'9905':'9905',
'1898':'1898',
'1872':'1872',
'1931':'1931',
'1637':'1637',
'1966':'1966',
'1912':'1912',
'1856':'1856',
'2018':'2018',
'1937':'1937',
'1961':'1961',
'1834':'1834',
'1997':'1997',
'1989':'1989',
'1994':'1994',
'1981':'1981',
'1968':'1968',
'1973':'1973',
'1971':'1971',
'1986':'1986',
'1678':'1678',
'2013':'2013',
'1977':'1977',
'2004':'2004',
'1607':'1607',
'1956':'1956',
'1967':'1967',
'1998':'1998',
'1934':'1934',
'1964':'1964',
'1999':'1999',
'1990':'1990',
'1312':'1312',
'1522':'1522',
'1941':'1941',
'2009':'2009',
'1919':'1919',
'2000':'2000',
'9906':'9906',
'1970':'1970'

}

varietal ={
"Loureiro-Arinto":"Loureiro-Arinto",
"Roviello":"Roviello",
"Pinot Noir-Gamay":"Pinot Noir-Gamay",
"Folle Blanche":"Folle Blanche",
"Trebbiano":"Trebbiano",
"Moscatel Graúdo":"Moscatel Graúdo",
"Sauvignon Blanc-Semillon":"Sauvignon Blanc-Semillon",
"Counoise":"Counoise",
"Verdelho":"Verdelho",
"Malvasia Fina":"Malvasia Fina",
"Petit Manseng":"Petit Manseng",
"Touriga Nacional Blend":"Touriga Nacional Blend",
"Alicante Bouschet":"Alicante Bouschet",
"Ruen":"Ruen",
"Kadarka":"Kadarka",
"Viura-Verdejo":"Viura-Verdejo",
"Primitivo-Susumaniello":"Primitivo-Susumaniello",
"Madeleine Angevine":"Madeleine Angevine",
"Carineña":"Carineña",
"Asprinio":"Asprinio",
"Prugnolo Gentile":"Prugnolo Gentile",
"Ekigaïna":"Ekigaïna",
"Alvarinho-Chardonnay":"Alvarinho-Chardonnay",
"Touriga Nacional":"Touriga Nacional",
"Sagrantino":"Sagrantino",
"Cinsault":"Cinsault",
"Cabernet Moravia":"Cabernet Moravia",
"Kerner":"Kerner",
"Pinot Blanc-Chardonnay":"Pinot Blanc-Chardonnay",
"Austrian Red Blend":"Austrian Red Blend",
"Picolit":"Picolit",
"Mazuelo":"Mazuelo",
"Grillo":"Grillo",
"Moscatel":"Moscatel",
"Carignan-Syrah":"Carignan-Syrah",
"Malbec-Carménère":"Malbec-Carménère",
"Fiano":"Fiano",
"Pugnitello":"Pugnitello",
"Malbec-Corvina":"Malbec-Corvina",
"Dolcetto":"Dolcetto",
"Verdeca":"Verdeca",
"Grecanico":"Grecanico",
"Syrah-Grenache":"Syrah-Grenache",
"Tempranillo-Tannat":"Tempranillo-Tannat",
"Pinotage":"Pinotage",
"Torbato":"Torbato",
"Moscatel de Alejandría":"Moscatel de Alejandría",
"Rhône-style Red Blend":"Rhône-style Red Blend",
"Premsal":"Premsal",
"Semillon-Chardonnay":"Semillon-Chardonnay",
"Chambourcin":"Chambourcin",
"Black Muscat":"Black Muscat",
"Lacrima":"Lacrima",
"Macabeo-Chardonnay":"Macabeo-Chardonnay",
"Graševina":"Graševina",
"Pecorino":"Pecorino",
"Uvalino":"Uvalino",
"Gewürztraminer-Riesling":"Gewürztraminer-Riesling",
"Albarín":"Albarín",
"Teroldego Rotaliano":"Teroldego Rotaliano",
"Tinto Velasco":"Tinto Velasco",
"Monastrell-Petit Verdot":"Monastrell-Petit Verdot",
"Ryzlink Rýnský":"Ryzlink Rýnský",
"Sauvignon Blanc-Verdejo":"Sauvignon Blanc-Verdejo",
"Hondarrabi Zuri":"Hondarrabi Zuri",
"Alvarelhão":"Alvarelhão",
"Sparkling Blend":"Sparkling Blend",
"Mourvèdre-Syrah":"Mourvèdre-Syrah",
"Otskhanuri Sapere":"Otskhanuri Sapere",
"Mataro":"Mataro",
"Mencía":"Mencía",
"Pigato":"Pigato",
"Agiorgitiko":"Agiorgitiko",
"Pinot Noir-Tannat":"Pinot Noir-Tannat",
"Hárslevelü":"Hárslevelü",
"Durella":"Durella",
"Fer Servadou":"Fer Servadou",
"Avesso":"Avesso",
"Bobal":"Bobal",
"Antão Vaz":"Antão Vaz",
"Malvazija":"Malvazija",
"Chelois":"Chelois",
"Picapoll":"Picapoll",
"Cabernet Sauvignon-Feteasca Neagra":"Cabernet Sauvignon-Feteasca Neagra",
"Garnacha Tintorera":"Garnacha Tintorera",
"Morio Muskat":"Morio Muskat",
"Syrah-Cabernet Sauvignon":"Syrah-Cabernet Sauvignon",
"Nasco":"Nasco",
"Listán Negro":"Listán Negro",
"Syrah-Tempranillo":"Syrah-Tempranillo",
"Other":"Other",
"Shiraz-Merlot":"Shiraz-Merlot",
"Shiraz-Cabernet":"Shiraz-Cabernet",
"Weisser Burgunder":"Weisser Burgunder",
"Boğazkere":"Boğazkere",
"Cercial":"Cercial",
"Rubin":"Rubin",
"Carmenère-Cabernet Sauvignon":"Carmenère-Cabernet Sauvignon",
"Riesling-Chardonnay":"Riesling-Chardonnay",
"Godello":"Godello",
"Roussanne":"Roussanne",
"Durif":"Durif",
"Cabernet-Syrah":"Cabernet-Syrah",
"Traminer":"Traminer",
"Cordisco":"Cordisco",
"Moscato di Noto":"Moscato di Noto",
"Charbono":"Charbono",
"Aidani":"Aidani",
"Malagouzia":"Malagouzia",
"Sciaccerellu":"Sciaccerellu",
"Trollinger":"Trollinger",
"Alfrocheiro":"Alfrocheiro",
"Shiraz-Cabernet Sauvignon":"Shiraz-Cabernet Sauvignon",
"Petroulianos":"Petroulianos",
"Tinta del Pais":"Tinta del Pais",
"Siegerrebe":"Siegerrebe",
"Port":"Port",
"Garnacha Blanca":"Garnacha Blanca",
"Cabernet Franc-Petit Verdot":"Cabernet Franc-Petit Verdot",
"Carnelian":"Carnelian",
"Cabernet Pfeffer":"Cabernet Pfeffer",
"Cerceal":"Cerceal",
"Rosenmuskateller":"Rosenmuskateller",
"Muskateller":"Muskateller",
"Shiraz-Grenache":"Shiraz-Grenache",
"Moscatel Roxo":"Moscatel Roxo",
"Pinot Noir":"Pinot Noir",
"Passerina":"Passerina",
"Tai":"Tai",
"Orangetraube":"Orangetraube",
"Királyleányka":"Királyleányka",
"Zelen":"Zelen",
"Caprettone":"Caprettone",
"Chenin Blanc-Viognier":"Chenin Blanc-Viognier",
"Petite Syrah":"Petite Syrah",
"Teroldego":"Teroldego",
"Gaglioppo":"Gaglioppo",
"Verdosilla":"Verdosilla",
"Monastrell-Cabernet Sauvignon":"Monastrell-Cabernet Sauvignon",
"Ehrenfelser":"Ehrenfelser",
"Garnatxa":"Garnatxa",
"Gros Manseng":"Gros Manseng",
"Primitivo":"Primitivo",
"Côt":"Côt",
"Raboso":"Raboso",
"Morava":"Morava",
"Canaiolo":"Canaiolo",
"Meritage":"Meritage",
"Maria Gomes-Bical":"Maria Gomes-Bical",
"Okuzgozu":"Okuzgozu",
"Negroamaro":"Negroamaro",
"Garnacha-Syrah":"Garnacha-Syrah",
"Pardina":"Pardina",
"Falanghina":"Falanghina",
"Aglianico":"Aglianico",
"Petit Verdot":"Petit Verdot",
"Savagnin":"Savagnin",
"Espadeiro":"Espadeiro",
"Kisi":"Kisi",
"Roter Traminer":"Roter Traminer",
"Cabernet Franc-Tempranillo":"Cabernet Franc-Tempranillo",
"Verduzzo Friulano ":"Verduzzo Friulano ",
"Nero di Troia":"Nero di Troia",
"Vranac":"Vranac",
"Syrah-Garnacha":"Syrah-Garnacha",
"Portuguese White":"Portuguese White",
"Jampal":"Jampal",
"Olasrizling":"Olasrizling",
"Shiraz-Pinotage":"Shiraz-Pinotage",
"Pallagrello":"Pallagrello",
"Pansa Blanca":"Pansa Blanca",
"Carmenère":"Carmenère",
"Morillon":"Morillon",
"Refosco":"Refosco",
"Mansois":"Mansois",
"Chardonnay-Macabeo":"Chardonnay-Macabeo",
"Muscat Blanc":"Muscat Blanc",
"Altesse":"Altesse",
"Cabernet Sauvignon Grenache":"Cabernet Sauvignon Grenache",
"Babosa Negro":"Babosa Negro",
"Cabernet Merlot":"Cabernet Merlot",
"Tempranillo-Syrah":"Tempranillo-Syrah",
"Colorino":"Colorino",
"Pinot Noir-Syrah":"Pinot Noir-Syrah",
"Diamond":"Diamond",
"Cariñena-Garnacha":"Cariñena-Garnacha",
"Xinomavro":"Xinomavro",
"Madeira Blend":"Madeira Blend",
"Tannat-Syrah":"Tannat-Syrah",
"Riesling-Muscat":"Riesling-Muscat",
"Grenache Noir":"Grenache Noir",
"Moristel":"Moristel",
"Cabernet Sauvignon-Shiraz":"Cabernet Sauvignon-Shiraz",
"Vespaiolo":"Vespaiolo",
"Liebfraumilch":"Liebfraumilch",
"Plavac Mali":"Plavac Mali",
"Babić":"Babić",
"Blatina":"Blatina",
"Malvasia Bianca":"Malvasia Bianca",
"Muscat Canelli":"Muscat Canelli",
"Garnacha":"Garnacha",
"Pallagrello Nero":"Pallagrello Nero",
"Zierfandler":"Zierfandler",
"Syrah-Viognier":"Syrah-Viognier",
"Shiraz":"Shiraz",
"Cayuga":"Cayuga",
"Ribolla Gialla":"Ribolla Gialla",
"Viura":"Viura",
"Maturana Blanca":"Maturana Blanca",
"Viognier-Marsanne":"Viognier-Marsanne",
"Chardonelle":"Chardonelle",
"Cabernet Sauvignon-Sangiovese":"Cabernet Sauvignon-Sangiovese",
"Trepat":"Trepat",
"Gamza":"Gamza",
"Picpoul Blanc":"Picpoul Blanc",
"Blauer Wildbacher":"Blauer Wildbacher",
"Zweigelt":"Zweigelt",
"Cabernet-Malbec":"Cabernet-Malbec",
"Verdejo-Viura":"Verdejo-Viura",
"Steen":"Steen",
"Gelber Muskateller":"Gelber Muskateller",
"Marsanne":"Marsanne",
"Alvarinho":"Alvarinho",
"Sauvignon Blanc-Assyrtiko":"Sauvignon Blanc-Assyrtiko",
"Pinot-Chardonnay":"Pinot-Chardonnay",
"Chinuri":"Chinuri",
"Žilavka":"Žilavka",
"Sherry":"Sherry",
"Merlot-Cabernet":"Merlot-Cabernet",
"Schiava":"Schiava",
"Lagrein-Dolcetto":"Lagrein-Dolcetto",
"Greco Bianco":"Greco Bianco",
"Aleatico":"Aleatico",
"Ugni Blanc-Colombard":"Ugni Blanc-Colombard",
"Melon":"Melon",
"Sarba":"Sarba",
"Merlot-Malbec":"Merlot-Malbec",
"Cabernet Franc-Merlot":"Cabernet Franc-Merlot",
"Paralleda":"Paralleda",
"Incrocio Manzoni":"Incrocio Manzoni",
"Saperavi-Merlot":"Saperavi-Merlot",
"Syrah-Cabernet Franc":"Syrah-Cabernet Franc",
"Nerello Mascalese":"Nerello Mascalese",
"St. Laurent":"St. Laurent",
"Yapincak":"Yapincak",
"Sangiovese Grosso":"Sangiovese Grosso",
"Dafni":"Dafni",
"Rufete":"Rufete",
"Sangiovese-Cabernet Sauvignon":"Sangiovese-Cabernet Sauvignon",
"Insolia":"Insolia",
"Bombino Bianco":"Bombino Bianco",
"Cabernet Sauvignon-Merlot-Shiraz":"Cabernet Sauvignon-Merlot-Shiraz",
"Pignolo":"Pignolo",
"Grenache Gris":"Grenache Gris",
"Lagrein":"Lagrein",
"Garganega":"Garganega",
"Cabernet Franc-Lemberger":"Cabernet Franc-Lemberger",
"Aragonês":"Aragonês",
"Weissburgunder":"Weissburgunder",
"Sémillon":"Sémillon",
"Mavrodaphne":"Mavrodaphne",
"Alsace white blend":"Alsace white blend",
"Roussanne-Marsanne":"Roussanne-Marsanne",
"Shiraz-Tempranillo":"Shiraz-Tempranillo",
"Nosiola":"Nosiola",
"Aragonez":"Aragonez",
"Riesling":"Riesling",
"Chardonnay-Pinot Blanc":"Chardonnay-Pinot Blanc",
"Norton":"Norton",
"Lidia":"Lidia",
"Malbec-Bonarda":"Malbec-Bonarda",
"Rieslaner":"Rieslaner",
"Johannisberg":"Johannisberg",
"Tinta Negra Mole":"Tinta Negra Mole",
"Posip":"Posip",
"Sauvignon":"Sauvignon",
"Malvasia":"Malvasia",
"Marsanne-Viognier":"Marsanne-Viognier",
"Casavecchia":"Casavecchia",
"Tinta Caiada":"Tinta Caiada",
"Muscat Ottonel":"Muscat Ottonel",
"Ondenc":"Ondenc",
"Viognier-Grenache Blanc":"Viognier-Grenache Blanc",
"Prosecco":"Prosecco",
"Erbaluce":"Erbaluce",
"Zweigelt-Pinot Noir":"Zweigelt-Pinot Noir",
"Pinot Blanc-Pinot Noir":"Pinot Blanc-Pinot Noir",
"Kuntra":"Kuntra",
"Pineau d'Aunis":"Pineau d'Aunis",
"Tinto Fino":"Tinto Fino",
"Garnatxa Blanca":"Garnatxa Blanca",
"Monica":"Monica",
"Nerello Cappuccio":"Nerello Cappuccio",
"Tempranillo Blend":"Tempranillo Blend",
"Zlahtina":"Zlahtina",
"Blauburger":"Blauburger",
"Timorasso":"Timorasso",
"Cagnulari":"Cagnulari",
"Sauvignon Blanc-Sauvignon Gris":"Sauvignon Blanc-Sauvignon Gris",
"Verdicchio":"Verdicchio",
"Papaskarasi":"Papaskarasi",
"País":"País",
"Trousseau Gris":"Trousseau Gris",
"Moschofilero-Chardonnay":"Moschofilero-Chardonnay",
"Arinto":"Arinto",
"Greco":"Greco",
"Shiraz-Roussanne":"Shiraz-Roussanne",
"Gewürztraminer":"Gewürztraminer",
"Lambrusco":"Lambrusco",
"Red Blend":"Red Blend",
"Jacquez":"Jacquez",
"Piquepoul Blanc":"Piquepoul Blanc",
"Lambrusco di Sorbara":"Lambrusco di Sorbara",
"Grenache-Carignan":"Grenache-Carignan",
"Muscatel":"Muscatel",
"Pinot Meunier":"Pinot Meunier",
"Tsolikouri":"Tsolikouri",
"Rhône-style White Blend":"Rhône-style White Blend",
"Roussanne-Grenache Blanc":"Roussanne-Grenache Blanc",
"Garnacha-Cariñena":"Garnacha-Cariñena",
"Barbera":"Barbera",
"Fumé-Chardonnay":"Fumé-Chardonnay",
"Muscadine":"Muscadine",
"Merlot-Cabernet Sauvignon":"Merlot-Cabernet Sauvignon",
"Orange Muscat":"Orange Muscat",
"Macabeo":"Macabeo",
"Azal":"Azal",
"Provence red blend":"Provence red blend",
"Nebbiolo":"Nebbiolo",
"Carignane":"Carignane",
"Bordeaux-style White Blend":"Bordeaux-style White Blend",
"Dorona":"Dorona",
"Çalkarası":"Çalkarası",
"Claret":"Claret",
"Sercial":"Sercial",
"Tinta de Toro":"Tinta de Toro",
"Vernaccia":"Vernaccia",
"Grolleau":"Grolleau",
"Rosé":"Rosé",
"Black Monukka":"Black Monukka",
"Roditis":"Roditis",
"Mavroudi":"Mavroudi",
"Cabernet Franc-Carmenère":"Cabernet Franc-Carmenère",
"Blaufränkisch":"Blaufränkisch",
"Xynisteri":"Xynisteri",
"Tempranillo":"Tempranillo",
"Cabernet Sauvignon-Barbera":"Cabernet Sauvignon-Barbera",
"Fiano Bianco":"Fiano Bianco",
"Grauburgunder":"Grauburgunder",
"Tinta Roriz":"Tinta Roriz",
"Cococciola":"Cococciola",
"Tămâioasă Românească":"Tămâioasă Românească",
"Carignan-Grenache":"Carignan-Grenache",
"Syrah":"Syrah",
"Rotgipfler":"Rotgipfler",
"Gamay Noir":"Gamay Noir",
"Bual":"Bual",
"Viura-Sauvignon Blanc":"Viura-Sauvignon Blanc",
"Maria Gomes":"Maria Gomes",
"Edelzwicker":"Edelzwicker",
"Pelaverga Piccolo":"Pelaverga Piccolo",
"Chardonnay-Pinot Gris":"Chardonnay-Pinot Gris",
"Carricante":"Carricante",
"Rabigato":"Rabigato",
"Chardonnay-Sauvignon Blanc":"Chardonnay-Sauvignon Blanc",
"Saperavi":"Saperavi",
"Aligoté":"Aligoté",
"Spätburgunder":"Spätburgunder",
"Cserszegi Fűszeres":"Cserszegi Fűszeres",
"Chardonel":"Chardonel",
"Savatiano":"Savatiano",
"Siria":"Siria",
"Muskat":"Muskat",
"Lambrusco Salamino":"Lambrusco Salamino",
"Monastrell":"Monastrell",
"Kallmet":"Kallmet",
"Gelber Traminer":"Gelber Traminer",
"Terret Blanc":"Terret Blanc",
"Alicante":"Alicante",
"Favorita":"Favorita",
"Brachetto":"Brachetto",
"Macabeo-Gewürztraminer":"Macabeo-Gewürztraminer",
"Syrah-Petit Verdot":"Syrah-Petit Verdot",
"Doña Blanca":"Doña Blanca",
"Syrah-Malbec":"Syrah-Malbec",
"Airen":"Airen",
"Friulano":"Friulano",
"Koshu":"Koshu",
"Baga-Touriga Nacional":"Baga-Touriga Nacional",
"Oseleta":"Oseleta",
"Foglia Tonda":"Foglia Tonda",
"Roscetto":"Roscetto",
"Viognier-Chardonnay":"Viognier-Chardonnay",
"Nascetta":"Nascetta",
"Elbling":"Elbling",
"Merlot-Syrah":"Merlot-Syrah",
"Cencibel":"Cencibel",
"Touriga Franca":"Touriga Franca",
"Syrah-Cabernet":"Syrah-Cabernet",
"Syrah-Grenache-Viognier":"Syrah-Grenache-Viognier",
"Argaman":"Argaman",
"Semillon-Sauvignon Blanc":"Semillon-Sauvignon Blanc",
"Mandilaria":"Mandilaria",
"Minutolo":"Minutolo",
"Rosado":"Rosado",
"Cabernet Sauvignon-Malbec":"Cabernet Sauvignon-Malbec",
"Maréchal Foch":"Maréchal Foch",
"Meoru":"Meoru",
"Tintilia ":"Tintilia ",
"Bacchus":"Bacchus",
"Muskat Ottonel":"Muskat Ottonel",
"Trincadeira":"Trincadeira",
"Rolle":"Rolle",
"Shiraz-Malbec":"Shiraz-Malbec",
"Flora":"Flora",
"Torrontés":"Torrontés",
"Encruzado":"Encruzado",
"Parraleta":"Parraleta",
"Merlot-Petite Verdot":"Merlot-Petite Verdot",
"Lemberger":"Lemberger",
"Arinto-Chardonnay":"Arinto-Chardonnay",
"Biancale":"Biancale",
"Saint Jeannet":"Saint Jeannet",
"Veltliner":"Veltliner",
"Poulsard":"Poulsard",
"Pinot Blanc-Viognier":"Pinot Blanc-Viognier",
"Jaen":"Jaen",
"Syrah-Carmenère":"Syrah-Carmenère",
"Malvasia di Candia":"Malvasia di Candia",
"Narince":"Narince",
"Lemberger-Cabernet":"Lemberger-Cabernet",
"Trajadura":"Trajadura",
"Trebbiano Spoletino":"Trebbiano Spoletino",
"Syrah-Xinomavro":"Syrah-Xinomavro",
"Feteascǎ Regalǎ":"Feteascǎ Regalǎ",
"Muscat Blanc à Petits Grains":"Muscat Blanc à Petits Grains",
"Picpoul":"Picpoul",
"Tokaji":"Tokaji",
"Sirica":"Sirica",
"Enantio":"Enantio",
"Traminette":"Traminette",
"Auxerrois":"Auxerrois",
"Carcajolu":"Carcajolu",
"White Blend":"White Blend",
"Viognier-Gewürztraminer":"Viognier-Gewürztraminer",
"Grenache-Shiraz":"Grenache-Shiraz",
"Viognier":"Viognier",
"Garnacha-Tempranillo":"Garnacha-Tempranillo",
"Vranec":"Vranec",
"Cabernet Sauvignon-Petit Verdot":"Cabernet Sauvignon-Petit Verdot",
"Códega do Larinho":"Códega do Larinho",
"Ciliegiolo":"Ciliegiolo",
"Marquette":"Marquette",
"Chardonnay-Semillon":"Chardonnay-Semillon",
"Coda di Volpe":"Coda di Volpe",
"Muscadelle":"Muscadelle",
"Trebbiano di Lugana":"Trebbiano di Lugana",
"Palomino":"Palomino",
"Malbec Blend":"Malbec Blend",
"White Port":"White Port",
"Raspberry":"Raspberry",
"Abouriou":"Abouriou",
"Sauvignon-Sémillon":"Sauvignon-Sémillon",
"Marsanne-Roussanne":"Marsanne-Roussanne",
"Verdil":"Verdil",
"Sacy":"Sacy",
"Pinot Nero":"Pinot Nero",
"Nero d'Avola":"Nero d'Avola",
"Corvina":"Corvina",
"Welschriesling":"Welschriesling",
"Cabernet-Shiraz":"Cabernet-Shiraz",
"Verdejo":"Verdejo",
"Gouveio":"Gouveio",
"Mavrotragano":"Mavrotragano",
"Chardonnay-Riesling":"Chardonnay-Riesling",
"Tocai Rosso":"Tocai Rosso",
"Bovale":"Bovale",
"Carignano":"Carignano",
"Tinta Miúda":"Tinta Miúda",
"Nieddera":"Nieddera",
"Manzoni":"Manzoni",
"Colombard-Sauvignon Blanc":"Colombard-Sauvignon Blanc",
"Mourvèdre":"Mourvèdre",
"Sousão":"Sousão",
"Pinot Grigio-Sauvignon Blanc":"Pinot Grigio-Sauvignon Blanc",
"Malbec":"Malbec",
"Forcallà":"Forcallà",
"Tinto del Pais":"Tinto del Pais",
"Catarratto":"Catarratto",
"Melon de Bourgogne":"Melon de Bourgogne",
"Piedirosso":"Piedirosso",
"Mavrokalavryta":"Mavrokalavryta",
"Blauburgunder":"Blauburgunder",
"Teran":"Teran",
"Kinali Yapincak":"Kinali Yapincak",
"$12 ":"$12 ",
"Tinta del Toro":"Tinta del Toro",
"Cannonau":"Cannonau",
"Terrantez":"Terrantez",
"Sangiovese Cabernet":"Sangiovese Cabernet",
"Tempranillo-Shiraz":"Tempranillo-Shiraz",
"Provence white blend":"Provence white blend",
"Grenache-Syrah":"Grenache-Syrah",
"Gros and Petit Manseng":"Gros and Petit Manseng",
"Crespiello":"Crespiello",
"Moscatel Galego Branco":"Moscatel Galego Branco",
"Souzao":"Souzao",
"Areni":"Areni",
"Sylvaner":"Sylvaner",
"Assyrtiko-Sauvignon Blanc":"Assyrtiko-Sauvignon Blanc",
"Franconia":"Franconia",
"Freisa":"Freisa",
"Cabernet Gernischt":"Cabernet Gernischt",
"Rebo":"Rebo",
"Tinta Cao":"Tinta Cao",
"Mondeuse":"Mondeuse",
"Garnacha Blend":"Garnacha Blend",
"Francisa":"Francisa",
"Malmsey":"Malmsey",
"Kalecik Karasi":"Kalecik Karasi",
"Chenin Blanc-Chardonnay":"Chenin Blanc-Chardonnay",
"Irsai Oliver":"Irsai Oliver",
"Tempranillo-Garnacha":"Tempranillo-Garnacha",
"Vignoles":"Vignoles",
"Baga":"Baga",
"Chardonnay-Pinot Grigio":"Chardonnay-Pinot Grigio",
"Petite Arvine":"Petite Arvine",
"Malvoisie":"Malvoisie",
"Garnacha-Graciano":"Garnacha-Graciano",
"St. Vincent":"St. Vincent",
"Montepulciano":"Montepulciano",
"Romorantin":"Romorantin",
"Malagousia":"Malagousia",
"Pinot Gris-Gewürztraminer":"Pinot Gris-Gewürztraminer",
"Touriga Nacional-Cabernet Sauvignon":"Touriga Nacional-Cabernet Sauvignon",
"Sangiovese-Syrah":"Sangiovese-Syrah",
"Cabernet Sauvignon":"Cabernet Sauvignon",
"Bobal-Tempranillo":"Bobal-Tempranillo",
"Tannat-Cabernet Franc":"Tannat-Cabernet Franc",
"Grenache Blend":"Grenache Blend",
"Vilana":"Vilana",
"Bukettraube":"Bukettraube",
"Vespolina":"Vespolina",
"Marzemino":"Marzemino",
"Bical":"Bical",
"Furmint":"Furmint",
"Chenin Blanc-Verdelho":"Chenin Blanc-Verdelho",
"Sangiovese":"Sangiovese",
"Ortega":"Ortega",
"Vinhão":"Vinhão",
"Jacquère":"Jacquère",
"Angevine":"Angevine",
"Rkatsiteli":"Rkatsiteli",
"Cesanese d'Affile":"Cesanese d'Affile",
"Malvar":"Malvar",
"Ojaleshi":"Ojaleshi",
"Touriga":"Touriga",
"Bordeaux-style Red Blend":"Bordeaux-style Red Blend",
"Roditis-Moschofilero":"Roditis-Moschofilero",
"Glera":"Glera",
"Portuguese Rosé":"Portuguese Rosé",
"Pinot Gris":"Pinot Gris",
"Marawi":"Marawi",
"Cabernet Sauvignon-Tempranillo":"Cabernet Sauvignon-Tempranillo",
"Cabernet Sauvignon-Syrah":"Cabernet Sauvignon-Syrah",
"Perricone":"Perricone",
"Pinot Grigio":"Pinot Grigio",
"Cabernet Blend":"Cabernet Blend",
"Ansonica":"Ansonica",
"Vermentino Nero":"Vermentino Nero",
"Tinta Barroca":"Tinta Barroca",
"Moscofilero":"Moscofilero",
"Cesanese":"Cesanese",
"Torontel":"Torontel",
"Moscato Giallo":"Moscato Giallo",
"Pinot Auxerrois":"Pinot Auxerrois",
"Malagouzia-Chardonnay":"Malagouzia-Chardonnay",
"Grasparossa di Castelvetro":"Grasparossa di Castelvetro",
"Ramisco":"Ramisco",
"Tocai Friulano":"Tocai Friulano",
"Malbec-Cabernet Sauvignon":"Malbec-Cabernet Sauvignon",
"Gamay":"Gamay",
"Chenin Blanc-Sauvignon Blanc":"Chenin Blanc-Sauvignon Blanc",
"Malbec-Cabernet Franc":"Malbec-Cabernet Franc",
"Robola":"Robola",
"Moscadello":"Moscadello",
"Rosato":"Rosato",
"Tempranillo-Merlot":"Tempranillo-Merlot",
"Tempranillo Blanco":"Tempranillo Blanco",
"Bonarda":"Bonarda",
"Bombino Nero":"Bombino Nero",
"Vidadillo":"Vidadillo",
"Trousseau":"Trousseau",
"Merlot-Cabernet Franc":"Merlot-Cabernet Franc",
"Muscat":"Muscat",
"Clairette":"Clairette",
"Merlot-Tannat":"Merlot-Tannat",
"Seyval Blanc":"Seyval Blanc",
"$17 ":"$17 ",
"Duras":"Duras",
"Rara Neagra":"Rara Neagra",
"Uva di Troia":"Uva di Troia",
"Nielluciu":"Nielluciu",
"Nuragus":"Nuragus",
"Moschofilero":"Moschofilero",
"Sauvignon Gris":"Sauvignon Gris",
"Boal":"Boal",
"Xarel-lo":"Xarel-lo",
"Zinfandel":"Zinfandel",
"Cabernet Sauvignon-Mourvèdre":"Cabernet Sauvignon-Mourvèdre",
"Tamianka":"Tamianka",
"Verdejo-Sauvignon Blanc":"Verdejo-Sauvignon Blanc",
"Merlot-Argaman":"Merlot-Argaman",
"Petit Courbu":"Petit Courbu",
"Müller-Thurgau":"Müller-Thurgau",
"Chardonnay Weissburgunder":"Chardonnay Weissburgunder",
"Zierfandler-Rotgipfler":"Zierfandler-Rotgipfler",
"Ruché":"Ruché",
"Mantonico":"Mantonico",
"Treixadura":"Treixadura",
"Segalin":"Segalin",
"Emir":"Emir",
"Tempranillo-Malbec":"Tempranillo-Malbec",
"Assyrtico":"Assyrtico",
"Assyrtiko":"Assyrtiko",
"Viosinho":"Viosinho",
"Muscat d'Alexandrie":"Muscat d'Alexandrie",
"Feteasca":"Feteasca",
"Petit Meslier":"Petit Meslier",
"Pied de Perdrix":"Pied de Perdrix",
"Misket":"Misket",
"Chardonnay":"Chardonnay",
"Tannat-Merlot":"Tannat-Merlot",
"Schwartzriesling":"Schwartzriesling",
"Bastardo":"Bastardo",
"Austrian white blend":"Austrian white blend",
"Chancellor":"Chancellor",
"Susumaniello":"Susumaniello",
"Carmenère-Syrah":"Carmenère-Syrah",
"Molinara":"Molinara",
"Cabernet Franc-Cabernet Sauvignon":"Cabernet Franc-Cabernet Sauvignon",
"Trebbiano-Malvasia":"Trebbiano-Malvasia",
"Albillo":"Albillo",
"Juhfark":"Juhfark",
"Prokupac":"Prokupac",
"Cabernet Sauvignon and Tinta Roriz":"Cabernet Sauvignon and Tinta Roriz",
"Monastrell-Syrah":"Monastrell-Syrah",
"Gros Plant":"Gros Plant",
"Petite Sirah":"Petite Sirah",
"Groppello":"Groppello",
"Prié Blanc":"Prié Blanc",
"Thrapsathiri":"Thrapsathiri",
"Cabernet Sauvignon-Merlot":"Cabernet Sauvignon-Merlot",
"Roussanne-Viognier":"Roussanne-Viognier",
"Sauvignonasse":"Sauvignonasse",
"Loin de l'Oeil":"Loin de l'Oeil",
"Muscat Hamburg":"Muscat Hamburg",
"Malbec-Tannat":"Malbec-Tannat",
"Karasakiz":"Karasakiz",
"Vitovska":"Vitovska",
"Manseng Noir":"Manseng Noir",
"Valvin Muscat":"Valvin Muscat",
"Fumé Blanc":"Fumé Blanc",
"Băbească neagră":"Băbească neagră",
"Bogdanjuša":"Bogdanjuša",
"Sauvignon Musqué":"Sauvignon Musqué",
"Shiraz-Mourvèdre":"Shiraz-Mourvèdre",
"Syrah-Bonarda":"Syrah-Bonarda",
"Inzolia":"Inzolia",
"Alvarinho-Trajadura":"Alvarinho-Trajadura",
"Apple":"Apple",
"Meseguera":"Meseguera",
"Syrah-Merlot":"Syrah-Merlot",
"Merlot-Grenache":"Merlot-Grenache",
"Viura-Chardonnay":"Viura-Chardonnay",
"Grenache Blanc":"Grenache Blanc",
"Chardonnay-Sauvignon":"Chardonnay-Sauvignon",
"Gragnano":"Gragnano",
"Centesimino":"Centesimino",
"Prunelard":"Prunelard",
"Moscato di Scanzo":"Moscato di Scanzo",
"Fernão Pires":"Fernão Pires",
"Vidal":"Vidal",
"Cabernet Franc":"Cabernet Franc",
"Barbera-Nebbiolo":"Barbera-Nebbiolo",
"Malbec-Tempranillo":"Malbec-Tempranillo",
"Castelão":"Castelão",
"Neuburger":"Neuburger",
"Portuguese Sparkling":"Portuguese Sparkling",
"Sumoll":"Sumoll",
"Debit":"Debit",
"Mtsvane":"Mtsvane",
"Sideritis":"Sideritis",
"Valdiguié":"Valdiguié",
"Cabernet Franc-Malbec":"Cabernet Franc-Malbec",
"Chardonnay-Viognier":"Chardonnay-Viognier",
"Portuguiser":"Portuguiser",
"Karalahna":"Karalahna",
"Grüner Veltliner":"Grüner Veltliner",
"Bobal-Cabernet Sauvignon":"Bobal-Cabernet Sauvignon",
"Champagne Blend":"Champagne Blend",
"Cabernet":"Cabernet",
"Chenin Blanc":"Chenin Blanc",
"Shiraz-Viognier":"Shiraz-Viognier",
"Grignolino":"Grignolino",
"Pignoletto":"Pignoletto",
"Tocai":"Tocai",
"Tinta Amarela":"Tinta Amarela",
"Tannat-Malbec":"Tannat-Malbec",
"Tannat":"Tannat",
"Albanello":"Albanello",
"Lambrusco Grasparossa":"Lambrusco Grasparossa",
"Baco Noir":"Baco Noir",
"Sauvignon Blanc":"Sauvignon Blanc",
"Ugni Blanc":"Ugni Blanc",
"Arneis":"Arneis",
"Symphony":"Symphony",
"Rivaner":"Rivaner",
"Sauvignon Blanc-Chenin Blanc":"Sauvignon Blanc-Chenin Blanc",
"Vermentino":"Vermentino",
"Durello":"Durello",
"Silvaner-Traminer":"Silvaner-Traminer",
"Colombard":"Colombard",
"Malbec-Petit Verdot":"Malbec-Petit Verdot",
"G-S-M":"G-S-M",
"Camarlet":"Camarlet",
"Pinotage-Merlot":"Pinotage-Merlot",
"Maturana":"Maturana",
"Pedro Ximénez":"Pedro Ximénez",
"Malbec-Merlot":"Malbec-Merlot",
"Muscadel":"Muscadel",
"Blauer Portugieser":"Blauer Portugieser",
"Malvasia Istriana":"Malvasia Istriana",
"Grenache-Mourvèdre":"Grenache-Mourvèdre",
"Rebula":"Rebula",
"Grenache":"Grenache",
"Frappato":"Frappato",
"Cortese":"Cortese",
"Traminac":"Traminac",
"Alcamo":"Alcamo",
"Xinisteri":"Xinisteri",
"Schioppettino":"Schioppettino",
"Magliocco":"Magliocco",
"Catalanesca":"Catalanesca",
"Viognier-Roussanne":"Viognier-Roussanne",
"Fumin":"Fumin",
"Kangoun":"Kangoun",
"Pinot Bianco":"Pinot Bianco",
"Blanc du Bois":"Blanc du Bois",
"Vidal Blanc":"Vidal Blanc",
"Biancolella":"Biancolella",
"Turbiana":"Turbiana",
"Moscato":"Moscato",
"Pallagrello Bianco":"Pallagrello Bianco",
"Negrette":"Negrette",
"Muscadet":"Muscadet",
"Moscato Rosa":"Moscato Rosa",
"Braucol":"Braucol",
"Grechetto":"Grechetto",
"Moreto":"Moreto",
"Marselan":"Marselan",
"Pinot Grigio-Chardonnay":"Pinot Grigio-Chardonnay",
"Verduzzo":"Verduzzo",
"Merlot":"Merlot",
"Plyto":"Plyto",
"Roter Veltliner":"Roter Veltliner",
"Carignan":"Carignan",
"Dornfelder":"Dornfelder",
"Prieto Picudo":"Prieto Picudo",
"Tinta Fina":"Tinta Fina",
"Frankovka":"Frankovka",
"Portuguese Red":"Portuguese Red",
"Tokay":"Tokay",
"Mauzac":"Mauzac",
"Chasselas":"Chasselas",
"Malbec-Cabernet":"Malbec-Cabernet",
"Malvasia Nera":"Malvasia Nera",
"Mavrud":"Mavrud",
"Melnik":"Melnik",
"Loureiro":"Loureiro",
"Syrah-Petite Sirah":"Syrah-Petite Sirah",
"Früburgunder":"Früburgunder",
"Caladoc":"Caladoc",
"Chardonnay-Albariño":"Chardonnay-Albariño",
"Tannat-Cabernet":"Tannat-Cabernet",
"Mission":"Mission",
"Tempranillo-Cabernet Sauvignon":"Tempranillo-Cabernet Sauvignon",
"Tamjanika":"Tamjanika",
"Cabernet Sauvignon-Carmenère":"Cabernet Sauvignon-Carmenère",
"Johannisberg Riesling":"Johannisberg Riesling",
"Huxelrebe":"Huxelrebe",
"Zibibbo":"Zibibbo",
"Bouchet":"Bouchet",
"Syrah-Carignan":"Syrah-Carignan",
"Kekfrankos":"Kekfrankos",
"Merlot-Shiraz":"Merlot-Shiraz",
"Garnacha-Cabernet":"Garnacha-Cabernet",
"Athiri":"Athiri",
"Sauvignon Blanc-Chardonnay":"Sauvignon Blanc-Chardonnay",
"Graciano":"Graciano",
"Ranchita Canyon":"Ranchita Canyon",
"Tokay Pinot Gris":"Tokay Pinot Gris",
"Tinta Francisca":"Tinta Francisca",
"Albariño":"Albariño",
"Bouvier":"Bouvier",
"Muscat of Alexandria":"Muscat of Alexandria",
"Colombard-Ugni Blanc":"Colombard-Ugni Blanc",
"Kotsifali":"Kotsifali",
"Pinot Blanc":"Pinot Blanc",
"Merseguera-Sauvignon Blanc":"Merseguera-Sauvignon Blanc",
"Vital":"Vital",
"Sämling":"Sämling",
"Albana":"Albana",
"Muscat-Viognier":"Muscat-Viognier",
"Macabeo-Moscatel":"Macabeo-Moscatel",
"Cabernet Sauvignon-Cabernet Franc":"Cabernet Sauvignon-Cabernet Franc",
"St. George":"St. George",
"Biancu Gentile":"Biancu Gentile",
"Albarossa":"Albarossa",
"Malbec-Syrah":"Malbec-Syrah",
"Viognier-Valdiguié":"Viognier-Valdiguié",
"Malvasia-Viura":"Malvasia-Viura",
"White Riesling":"White Riesling",
"Tsapournakos":"Tsapournakos",
"Syrah-Mourvèdre":"Syrah-Mourvèdre",
"Viognier-Pinot Gris":"Viognier-Pinot Gris",
"Scheurebe":"Scheurebe",
"Garnacha-Monastrell":"Garnacha-Monastrell",
"Feteasca Neagra":"Feteasca Neagra",
"Silvaner":"Silvaner"
}