# Generated by Django 3.0.5 on 2020-04-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllWines',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_column='ID', primary_key=True, serialize=False)),
                ('alcohol', models.FloatField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('designation', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('rating', models.BigIntegerField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('subregion', models.TextField(blank=True, null=True)),
                ('subsubregion', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('varietal', models.TextField(blank=True, null=True)),
                ('vintage', models.FloatField(blank=True, null=True)),
                ('winery', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'all_wines',
                'managed': False,
            },
        ),
    ]
